name: sycs_proj_shikha
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_auth_web: ^5.10.1
  web: ^0.5.1
  fluttertoast: ^8.0.8
  http: ^1.2.1
  path_provider: ^2.1.2
  cloud_firestore: ^4.15.10
  provider: ^6.1.2
  flutter_downloader: ^1.11.6
  foundation: ^0.0.5
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  social_share: ^2.3.1
  share_plus: ^8.0.3
  social_share_plus: ^0.0.4
  clipboard: ^0.1.3
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2


flutter:


  uses-material-design: true

  assets:
    - images/front1.jpg
    - images/tree.jpg
    - images/login.jpg
    - images/img1.jpg
    - images/img3.jpg
    - images/img2.jpg
    - images/girl.jpg
    - images/sneha.jpg


  fonts:
     - family: DancingScript
       fonts:
         - asset: fonts/DancingScript-Regular.ttf
     - family: RubikScribble
       fonts:
         - asset: fonts/RubikScribble-Regular.ttf
     - family: Anton
       fonts:
         - asset: fonts/Anton-Regular.ttf
     - family: MadimiOne
       fonts:
         - asset: fonts/MadimiOne-Regular.ttf
     - family: RobotoMono
       fonts:
         - asset: fonts/RobotoMono-Regular.ttf
